### ISSUE TITLE
[platformIO] tnfs_readdir should skip right over System Volume Information folder.

### ISSUE THREAD

**Issue by tschak909** [FujiNetWIFI/fujinet-platformio#134]
As this folder is created by Windows, and can't be side-stepped, and is useless to #FujiNet users, it should be skipped over during a tnfslib::readdir()

-Thom

**Comment by FujiMan66** [comment]
Is there any other files/folders that would also need to be skipped? .AppleDouble, .DS_Store, .Trash-1000, 'Network Trash Items", etc. that Windows/Mac/Linux creates for internal use?

**Comment by tschak909** [comment]
Yup, pretty much all of the above! :)

-Thom

**Comment by kaelef** [comment]
This is really better handled at the server side, since the client doesn't get any useful information about these files (no flag that indicates that it's hidden, for example).  Outside of that preferred option, we'd simply have to maintain a cross-platform list of names to skip.

**Comment by kaelef** [comment]
Server side code now handles this
