### ISSUE TITLE
Networking for the Atari

### ISSUE THREAD

**Issue by Technoid6502** [FujiNetWIFI/fujinet-platformio#21]
I'm completely new at this and probably breaking etiquette, but it seems a waste not to put my 2 cents in and this is where I found to do it.

Networking for the Atari is really exciting, has huge potential and I'm really glad you are working on it.

I'm interested in some functions, aren't the hardware guys always?  Basically, if you read the documentation to the CSS Multiplexer, you will see a pretty good model of a rich Mux implementation.  The Master machine, who's purpose is to provide peripherals to the 'slaves', also dedicates a chunk of memory to a number of pipes, 1k and 128byte pipes, which allows the slaves to exchange information in blocks via simple XIO calls, provided cio to these pipes.

So, to the degree you can, could you see some of this semaphore, message pipe, and other stuff allows intercommunication between connected devices without having to resort to a shared disk?

The Mux architecture isn't all that important, but the CSS Mux provided some hellacious capability noone really thought to use.  I had one and didn't think of it til' way too late.  Basically, I'd like to use your devices as the backbone to an Atari 8-bit parallel multiprocessor solving some knotty problem within it's abilities.  It would be FUN!

Best,
Jeff

**Comment by tschak909** [comment]
You will have the ability to create TCP sockets and UDP datagrams, this can
be used to create any higher level networking protocol.

My goal here is to give these basic tools, make it easy to use, and to hand
it to others who can make any higher level abstractions. That is the plan.

-Thom
