### ISSUE TITLE
New Disk fails to create 16MB disk on SD card storage.

### ISSUE THREAD

**Issue by tschak909** [FujiNetWIFI/fujinet-platformio#306]
In Config:

New Disk
Any disk name.
Any device Slot
Host Slot "SD"
number of sectors: 65535
sector size: 256

What should happen:
a 16 megabyte disk should be created

What does happen
a 0 byte file is created.

**Comment by mozzwald** [comment]
I just tested this from commit a9d335f0b722eb658758be476c91cb94743ca761 in the tnfs2 branch and it works. I get a 16.8MB ATR on the SD card.

**Comment by kaelef** [comment]
Also unable to reproduce this despite various attempts
