### ISSUE TITLE
CONFIG, running on Atari, should be able to show #FujiNet firmware version

### ISSUE THREAD

**Issue by billkendrick** [FujiNetWIFI/fujinet-platformio#373]
At the moment, you need to point a web browser to the #FujiNet's web config page to see which version of the firmware you are running (i.e., to compare with what's listed at https://fujinet.online/download/). It would be nice if this appeared in the "#FUJINET CONFIG" screen that CONFIG tool on the Atari shows when you press `[C]` on some screens.

**Comment by billkendrick** [comment]
The display on the Atari should therefore re-label the CONFIG version shown (e.g., "`Version:2.5.2020-08-25`") as something less ambiguous (e.g., "`CONFIG Version: 2.6.2020-10-16`), with the new one being "`FujiNet Version: ...`" or "`Firmware Version: ...`", for example.

**Comment by tschak909** [comment]
Fixed as of this morning.
![WIN_20201016_12_39_23_Pro](https://user-images.githubusercontent.com/2759782/96329474-d1306e80-1012-11eb-8b9c-49d252d2beda.jpg)

**Comment by billkendrick** [comment]
Thanks @tschak909 -- It looks like the "CONFIG" version disappeared, though. Wouldn't it be handy (for debugging) to mention both?

Is it possible to run a #FujiNet with CONFIG version X built-in, but instead boot onto a separate disk that runs CONFIG version Y? (Admittedly an uncommon thing to do, I think... but perhaps useful if someone wants to try out a newer build of CONFIG, or revert to an earlier version due to a regression.)
