### ISSUE TITLE
Midimaze mode does not start SIO clock.

### ISSUE THREAD

**Issue by tschak909** [FujiNetWIFI/fujinet-platformio#377]
Midimaze does not start SIO clock when asked by web admin.

**Comment by mozzwald** [comment]
Debug output:

> 10:16:17.487 > E (43999) ledc: requested frequency and duty resolution can not be achieved, try reducing freq_hz or duty_resolution. div_param=0
10:16:17.487 > set_baudrate change from 19200 to 31250
10:16:17.488 > MIDIMAZE mode enabled
