### ISSUE TITLE
Change Hostname on FujiNet device 

### ISSUE THREAD

**Issue by TechCowboy** [FujiNetWIFI/fujinet-platformio#383]
Hostname can be changed via fnconfig.ini, but it would be nice to have that on the device webpage.

**Comment by tschak909** [comment]
HTML/CSS front done.
![image](https://user-images.githubusercontent.com/2759782/97909704-42a83680-1d0e-11eb-9693-623ecd109bc9.png)

**Comment by tschak909** [comment]
Implemented. Will be in next build.
