### ISSUE TITLE
Enhancement - Display Time Zone on FujiNet Device

### ISSUE THREAD

**Issue by TechCowboy** [FujiNetWIFI/fujinet-platformio#391]
Might be clearer to put AST/ADT
Selecting Atlantic time shows +4 which is confusing as it is UTC -4
![image](https://user-images.githubusercontent.com/2847372/98543278-9b288800-2268-11eb-8206-d698b495875a.png)

**Comment by mozzwald** [comment]
Time zones in FujiNet follow the [POSIX standard](https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html):

> The offset specifies the time value you must add to the local time to get a Coordinated Universal Time value. It has syntax like [+|-]hh[:mm[:ss]]. This is positive if the local time zone is west of the Prime Meridian and negative if it is east. The hour must be between 0 and 24, and the minute and seconds between 0 and 59.

which means UTC-4 / America Atlantic is correctly identified as _AST+4ADT_. I'm closing this issue as I don't think it's a problem. The ? link next to the Save button provides details about the proper format of the time zones.
