### ISSUE TITLE
Enhancement: Collecting PDF from Printer

### ISSUE THREAD

**Issue by TechCowboy** [FujiNetWIFI/fujinet-platformio#403]
Grayed out text hard to read _Click to download your current print-out_ 
It should also say Click on Icon OR include the text in the link area.

**Comment by tschak909** [comment]
on it.

**Comment by tschak909** [comment]
![image](https://user-images.githubusercontent.com/2759782/100033415-c611f080-2dbf-11eb-846c-b57d5ac09013.png)
