### ISSUE TITLE
BUG: Atari printers do not support inverse characters

### ISSUE THREAD

**Issue by TechCowboy** [FujiNetWIFI/fujinet-platformio#404]
Tried all the Atari printers and none of them supported inverse, only the ATASCII printer did
Don't know if this was the case with actual hardware or not.

**Comment by TechCowboy** [comment]
Fujicycle listing contains inverse characters in BASIC listing.
atari-apps.irata.online/Networking/n-handler/fujicycles.atr

**Comment by tschak909** [comment]
The Atari printers do not support inverse characters (or ATASCII
characters), this is why we made the ATASCII printer. :)

-Thom
