### ISSUE TITLE
Freature Request: Power on to BT (or last used mode)

### ISSUE THREAD

**Issue by schlutech** [FujiNetWIFI/fujinet-platformio#419]
The Fujinet is a pretty functional sio2bt device. It is unwanted though that it should always default back to Fujinet "mode" on power cycle. 

It seems to make sense that the unit, which already remembers host and disk configurations, also remember which mode it was last in so it can start back in that mode again. This way sio2bt is less of an after thought. 

Additional Justification: Currently on v1.0 hardware it is possible to get much faster transfer rates at times using sio2bt.

**Comment by mozzwald** [comment]
Fixed with cc1aca3b63d62a47cd421ae1a00ef28e5f20fdf5
