### ISSUE TITLE
CAS files need to be closed

### ISSUE THREAD

**Issue by delysio** [FujiNetWIFI/fujinet-platformio#420]
There is not a easy way to load CAS file, which was saved. User has to unmount the file after saving and mount it to be able to use it again.

**Comment by tschak909** [comment]
@delysio would it be sufficient to add a rewind button on the web admin, to start?

**Comment by tschak909** [comment]
(sorry, I've had my head down, and just saw this, maybe I can knock it out.)

**Comment by tschak909** [comment]
![image](https://user-images.githubusercontent.com/2759782/104779445-c20da980-5744-11eb-83d2-9418ba4e9ced.png)

**Comment by delysio** [comment]
Perfect. Thank you @tschak909
