### ISSUE TITLE
Need a way to query and filter JSON (like libjq, if not libjq itself)

### ISSUE THREAD

**Issue by tschak909** [FujiNetWIFI/fujinet-platformio#445]
Just as with #444 we need a way to do the same for JSON.
https://github.com/stedolan/jq

**Comment by idolpx** [comment]
This is very good.  I've used it but not in ESP-IDF.

https://github.com/bblanchon/ArduinoJson

**Comment by idolpx** [comment]
A bit of info to get it to work.

https://community.platformio.org/t/arduinojson-with-esp-idf/19027

**Comment by idolpx** [comment]
This also may be an option.

https://github.com/nlohmann/json

**Comment by tschak909** [comment]
closed, as we implemented using the path functions in cJSON.
