### ISSUE TITLE
Wiki FujiNet-Quickstart-Guide.md: added note about mixed WiFi

### ISSUE THREAD

**Issue by spicyjack** [FujiNetWIFI/fujinet-platformio#450]
As per [discussion](https://atariage.com/forums/topic/298720-fujinet-a-wip-sio-network-adapter-for-the-atari-8-bit/?do=findComment&comment=4827670) on [AtariAge](https://atariage.com/forums/topic/298720-fujinet-a-wip-sio-network-adapter-for-the-atari-8-bit/?do=findComment&comment=4827753), attached is a patch for updating the Quickstart guide with a note about using mixed 2.4GHz/5GHz WiFi networks (using both frequencies with the same SSID).  Patch created with `git format-patch`, but I had to rename it to `*.txt` to keep the GitHubs happy.

[0001-FujiNet-Quickstart-Guide.md-added-note-about-mixed-W.patch.txt](https://github.com/FujiNetWIFI/fujinet-platformio/files/6535398/0001-FujiNet-Quickstart-Guide.md-added-note-about-mixed-W.patch.txt)

**Comment by mozzwald** [comment]
Patch applied to the Wiki, thank you!
