### ISSUE TITLE
Add a TOC to the Quickstart Wiki page

### ISSUE THREAD

**Issue by spicyjack** [FujiNetWIFI/fujinet-platformio#451]
The Quickstart page has a lot of good info, but it's a bit hard hard to navigate in it's current form.

I (hopefully) added a Table of Contents that reuses the automatic links that GitHub uses for Markdown headings in wiki pages.

The downside to having a page TOC is you'll have to keep it updated with any changes to the page going forward.   If the thought of maintaining the TOC going forward is not appealing, I'm okay with not applying this patch.

I'm actually curious to see if the Markdown link anchors that make up the TOC work, I think they should, but I could be wrong.

[quickstart_guide_toc.patch.txt](https://github.com/FujiNetWIFI/fujinet-platformio/files/6596560/quickstart_guide_toc.patch.txt)

**Comment by tschak909** [comment]
Folded in! Thank you! :)
