### ISSUE TITLE
enable/disable SIO2BT via web config

### ISSUE THREAD

**Issue by marcowy** [FujiNetWIFI/fujinet-platformio#453]
I have custom PCB without buttons. It would be helpful to have such an option.

**Comment by mozzwald** [comment]
This should be possible, will look into it.

**Comment by mozzwald** [comment]
Now that I think about it, this may be difficult in practice. You would be able to turn on SIO2BT from the web interface, but when you do Wifi is disabled and Bluetooth enabled. I'm not sure if both can be enabled at the same time.

**Comment by mozzwald** [comment]
> I have custom PCB without buttons. It would be helpful to have such an option.

I can add the ability to enable SIO2BT mode from the web admin but you will not be able to turn it off without removing the sd card and editing fnconfig.ini to disable SIO2BT mode. Will this work for you? Maybe you should just add buttons to your hardware.

**Comment by marcowy** [comment]
I've added the button. Thanks!
