### ISSUE TITLE
[fnjson] will not return values larger than 2147483647.

### ISSUE THREAD

**Issue by tschak909** [FujiNetWIFI/fujinet-platformio#512]
Currently values larger than 2147483647, return 2147483647. If number is larger, return the double.

**Comment by DaBaDa79** [comment]
Tested, does not work because the check if larger than 2147483647 is done with the 32 bit int value which never can be true.
Case should be reopened.

**Comment by tschak909** [comment]
@DaBaDa79 thank you for hacking on this, You can do a PR to this bug. :)

-Thom
